### ISSUE TITLE
Slider resize doesn't work -> only container with slider is resized.

### ISSUE THREAD

**Issue by wszczepanski97** [Samsung/TAU-Design-Editor#238]
## Technical
Platform: WATT/VSC,
Profile: only Mobile 
## Description
Slider component resize doesn't work and in preview mode it looks strange
## Steps to reproduce
1. Create a new project in Design Editor
2. d&d slider to template.
3. Resize slider to be bigger/smaller
## Expected behaviour
All parts of slider are resized.
## Actual behaviour
Only gray part of slider changed its size.

**Comment by lslachciak** [comment]
@wszczepanski97 please specify platform for issue: wearable? mobile?

**Comment by lslachciak** [comment]
@wszczepanski97 this issue was fixed?

**Comment by wszczepanski97** [comment]
@lslachciak problem still exists, slider is not resized correctly.

**Comment by lslachciak** [comment]
Duplicate of https://github.com/Samsung/TAU-Design-Editor/issues/244
